services:
  pg:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=pg
      - POSTGRES_PASSWORD=pg
      - POSTGRES_DB=db
    volumes:
      - ./.volumes:/var/lib/postgresql/data
  pgadmin4:
    depends_on:
      - pg
