version: "3"
services:
  mysql:
    image: mysql:latest
    container_name: iteam-mysql-db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=pw
      - MYSQL_DATABASE=db
    volumes:
      - ./.volumes/mysql:/var/lib/mysql
  mysql-workbench:
    image: lscr.io/linuxserver/mysql-workbench:latest
    container_name: iteam-mysql-workbench
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./config:/config
    ports:
      - 3000:3000
      - 3001:3001
    cap_add:
      - IPC_LOCK
    restart: unless-stopped
